### ISSUE TITLE
Pressing `space` refreshes the icebreakers continuously

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/icebreakers#1]
When pressing and holding (even if done for a fraction of a second) the <kbd>space</kbd> bar, the icebreakers refresh continuously, which can be disorienting. 

**Expected behavior:**
- Pressing and/or holding down <kbd>space</kbd> should only refresh the icebreaker once
- A new icebreaker should be shown only if I release and press <kbd>space</kbd> again

**Comment by BartoszJarocki** [comment]
@enriquesanchez good point, you can try now, should be fixed

**Comment by enriquesanchez** [comment]
@BartoszJarocki This is soooo much better now. Thank you! 🙌
