### ISSUE TITLE
Removing secondary button

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/icebreakers#5]
I want to suggest we remove the `Copy this icebreaker URL` button from the card. Despite having a white background, it takes up much more space than the main `Refresh` CTA, competing for attention. Removing also has the added benefit of simplifying the card.

![imagen](https://user-images.githubusercontent.com/3276087/181839473-cc325117-4e81-40e5-a773-1d6a7a1aa5a2.png)

We can place it just under the card, and style it like a text button instead.

@BartoszJarocki What do you think?

**Comment by BartoszJarocki** [comment]
I like it! wanna do it?

**Comment by enriquesanchez** [comment]
Thanks @BartoszJarocki!

>I like it! wanna do it?

I will give it a try 😄 

>add a link or copy icon 

Oh, fantastic idea! Will do!
